/**
 * Draft Management API
 *
 * GET /api/drafts - List drafts with filters
 * POST /api/drafts - Create a new draft
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

/**
 * GET /api/drafts
 * List drafts with filters
 *
 * Query params:
 * - status: Filter by status (draft, sent, copied)
 * - workspaceId: Filter by workspace
 * - channelId: Filter by channel
 * - limit: Number of results (default 50)
 * - offset: Pagination offset
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);

    const status = searchParams.get('status');
    const workspaceId = searchParams.get('workspaceId');
    const channelId = searchParams.get('channelId');
    const limit = parseInt(searchParams.get('limit') || '50', 10);
    const offset = parseInt(searchParams.get('offset') || '0', 10);

    // Build where clause
    const where: any = {};

    if (status) {
      where.status = status;
    }

    if (workspaceId) {
      where.workspace_id = workspaceId;
    }

    if (channelId) {
      where.channel_id = channelId;
    }

    // Fetch drafts
    const [drafts, totalCount] = await Promise.all([
      prisma.draft.findMany({
        where,
        select: {
          id: true,
          message_id: true,
          workspace_id: true,
          channel_id: true,
          thread_ts: true,
          text: true,
          status: true,
          sent_via: true,
          analysis_run_id: true,
          created_at: true,
          updated_at: true,
          // Include related message if exists
          message: {
            select: {
              slack_ts: true,
              slack_channel_id: true,
              user_name: true,
              text: true,
            },
          },
          // Include workspace name
          workspace: {
            select: {
              name: true,
              team_id: true,
            },
          },
        },
        orderBy: {
          created_at: 'desc',
        },
        take: limit,
        skip: offset,
      }),
      prisma.draft.count({ where }),
    ]);

    return NextResponse.json({
      drafts,
      pagination: {
        total: totalCount,
        limit,
        offset,
        hasMore: offset + limit < totalCount,
      },
    });
  } catch (error) {
    console.error('Error fetching drafts:', error);
    return NextResponse.json(
      {
        error: 'Failed to fetch drafts',
        message: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}

/**
 * POST /api/drafts
 * Create a new draft
 *
 * Body: {
 *   text: string (required),
 *   workspaceId: string (required),
 *   channelId: string (required),
 *   threadTs?: string (optional - for thread replies),
 *   messageId?: string (optional - reference to original message),
 *   analysisRunId?: string (optional - if generated by analysis)
 * }
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { text, workspaceId, channelId, threadTs, messageId, analysisRunId } = body;

    // Validation
    if (!text || typeof text !== 'string' || text.trim().length === 0) {
      return NextResponse.json(
        { error: 'text is required and must be a non-empty string' },
        { status: 400 }
      );
    }

    if (!workspaceId || typeof workspaceId !== 'string') {
      return NextResponse.json(
        { error: 'workspaceId is required' },
        { status: 400 }
      );
    }

    if (!channelId || typeof channelId !== 'string') {
      return NextResponse.json(
        { error: 'channelId is required' },
        { status: 400 }
      );
    }

    // Verify workspace exists and is active
    const workspace = await prisma.workspace.findUnique({
      where: { id: workspaceId },
      select: { id: true, status: true },
    });

    if (!workspace) {
      return NextResponse.json(
        { error: 'Workspace not found' },
        { status: 404 }
      );
    }

    if (workspace.status !== 'active') {
      return NextResponse.json(
        { error: 'Workspace is not active' },
        { status: 403 }
      );
    }

    // Create draft
    const draft = await prisma.draft.create({
      data: {
        text: text.trim(),
        workspace_id: workspaceId,
        channel_id: channelId,
        thread_ts: threadTs || null,
        message_id: messageId || null,
        analysis_run_id: analysisRunId || null,
        status: 'draft',
      },
      include: {
        workspace: {
          select: {
            name: true,
            team_id: true,
          },
        },
      },
    });

    return NextResponse.json(
      {
        draft,
      },
      { status: 201 }
    );
  } catch (error) {
    console.error('Error creating draft:', error);
    return NextResponse.json(
      {
        error: 'Failed to create draft',
        message: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
